### ISSUE TITLE
[Bug Report]: Error during pip install: whoisit

### ISSUE THREAD

**Issue by lint-os** [sanjacob/BlackboardSync#403]
### BlackboardSync Version

0.17.2-rc.1

### BlackboardSync Release

PyPI, git

### Python Version

Python 3.10.12

### Operating System and Version

Linux Mint 21.2

### University Name

N/A

### Problem Description

After installing blackboardsync, and trying to run the program, you get this error message:
`Traceback (most recent call last):
  File "/home/USERNAME/build/blackboardsync/venv/bin/blackboardsync", line 5, in <module>
    from blackboard_sync import __main__
  File "/home/USERNAME/build/blackboardsync/venv/lib/python3.10/site-packages/blackboard_sync/__main__.py", line 24, in <module>
    from .sync_controller import SyncController
  File "/home/USERNAME/build/blackboardsync/venv/lib/python3.10/site-packages/blackboard_sync/sync_controller.py", line 26, in <module>
    from .sync import BlackboardSync
  File "/home/USERNAME/build/blackboardsync/venv/lib/python3.10/site-packages/blackboard_sync/sync.py", line 38, in <module>
    from .institutions import Institution, get_by_index
  File "/home/USERNAME/build/blackboardsync/venv/lib/python3.10/site-packages/blackboard_sync/institutions.py", line 26, in <module>
    from .ip import find_my_ip, find_ip_entity
  File "/home/USERNAME/build/blackboardsync/venv/lib/python3.10/site-packages/blackboard_sync/ip.py", line 20, in <module>
    import whoisit
ModuleNotFoundError: No module named 'whoisit'`
This can be solved with a `pip install whoisit` , but it would be nice if that was automatic. My guess is that the dependencies file is misconfigured. This issue also was present on Debian 12 when I installed it from the repo.

**Comment by sanjacob** [comment]
Thanks for the heads-up. Indeed it was missing from pyproject.toml
